/* limpiar historico planillas la 115 que no tenga valor calculo
esto se origina por las semanas de vacaciones de empleados, que no tienen 7o en esa quincena*/

SELECT     CODIGO_BIC, CODIGO_CLASE_DE_PLANILLA, CODIGO_TIPO_DE_PLANILLA, ANO_PLANILLA, PERIODO_PLANILLA, CODIGO_DEF_TRN_PLANILLA, 
                      FECHA_GRABADO, VALOR_CALCULO, DIAS_CALCULO, HORAS_CALCULO, UNIDADES_CALCULO, DESCRIPCION_DE_TRANSACCIO, 
                      CODIGO_DE_CUENTA
FROM         PLANILLA_HISTORICA
WHERE     (ANO_PLANILLA = 2016) AND (CODIGO_DEF_TRN_PLANILLA = '115') AND (VALOR_CALCULO = 0)




DELETE FROM PLANILLA_HISTORICA
WHERE     (ANO_PLANILLA = 2016) AND (CODIGO_DEF_TRN_PLANILLA = '115') AND (VALOR_CALCULO = 0)


