CREATE TABLE [dbo].[EMPLEADO_HISTORIAL_CAMBIOS](
	[NUMERO_DE_REGISTRO] [numeric](9, 0) NOT NULL,
	[CODIGO_BIC] [char](8) NULL,
	[STRING_ANTERIOR] [varchar](1024) NULL,
	[STRING_NUEVO] [varchar](1024) NULL,
	[TIPO_REGISTRO] [char](1) NULL,
	[HORA_ADICION] [datetime] NULL,
	[FECHA_ADICION] [datetime] NULL,
	[USUARIO_ADICION] [varchar](128) NULL,
	[HORA_ULTIMO_CAMBIO] [datetime] NULL,
	[FECHA_ULTIMO_CAMBIO] [datetime] NULL,
	[USUARIO_ULTIMO_CAMBIO] [varchar](128) NULL,
PRIMARY KEY CLUSTERED 
(
	[NUMERO_DE_REGISTRO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[EMPLEADO_HISTORIAL_CAMBIOS]  WITH CHECK ADD FOREIGN KEY([CODIGO_BIC])
REFERENCES [dbo].[EMPLEADO_TABLA] ([CODIGO_BIC])
GO


