BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.TRN_CONTABLE_HISTORIC3N9T_CEF ADD
	ORDEN_ETAPA_CULTIVO int NULL
GO
ALTER TABLE dbo.TRN_CONTABLE_HISTORIC3N9T_CEF SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

update TRN_CONTABLE_HISTORIC3N9T_CEF
set ORDEN_ETAPA_CULTIVO = 0