
/****** Object:  Table [dbo].[SOLICITUD_REQ_DE_COMPRA_DT_DA]    Script Date: 05/03/2016 10:17:46 a.m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SOLICITUD_REQ_DE_COMPRA_DT_DA](
	[PREFIJO_PARTIDA_CONTABLE] [char](6) NOT NULL,
	[NUMERO_SOLICITUD_COMPRA] [int] NOT NULL,
	[LINEA] [int] NOT NULL,
	[CODIGO_ALTERNO_DE_ARTICUL] [char](15) NULL,
	[NOMBRE_MARCA] [char](20) NULL,
	[NOMBRE_MODELO] [char](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[PREFIJO_PARTIDA_CONTABLE] ASC,
	[NUMERO_SOLICITUD_COMPRA] ASC,
	[LINEA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[SOLICITUD_REQ_DE_COMPRA_DT_DA]  WITH CHECK ADD FOREIGN KEY([PREFIJO_PARTIDA_CONTABLE], [NUMERO_SOLICITUD_COMPRA], [LINEA])
REFERENCES [dbo].[SOLICITUD_REQ_DE_COMPRA_DT] ([PREFIJO_PARTIDA_CONTABLE], [NUMERO_SOLICITUD_COMPRA], [LINEA])
GO


