
/****** Object:  Table [dbo].[ORDEN_DE_COMPRA_DATOS]    Script Date: 05/03/2016 10:18:51 a.m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ORDEN_DE_COMPRA_DATOS](
	[NUMERO_ORDEN_DE_COMPRA] [int] NOT NULL,
	[CODIGO_DE_AGENCIA] [int] NOT NULL,
	[NUMERO_DE_LINEA] [int] NOT NULL,
	[NOMBRE_MARCA] [char](20) NULL,
	[NOMBRE_MODELO] [char](20) NULL,
	[CODIGO_ALTERNO_DE_ARTICUL] [char](15) NULL,
PRIMARY KEY CLUSTERED 
(
	[NUMERO_ORDEN_DE_COMPRA] ASC,
	[CODIGO_DE_AGENCIA] ASC,
	[NUMERO_DE_LINEA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[ORDEN_DE_COMPRA_DATOS]  WITH CHECK ADD FOREIGN KEY([NUMERO_ORDEN_DE_COMPRA], [CODIGO_DE_AGENCIA], [NUMERO_DE_LINEA])
REFERENCES [dbo].[ORDEN_COMPRA_DET] ([NUMERO_ORDEN_DE_COMPRA], [CODIGO_DE_AGENCIA], [NUMERO_DE_LINEA])
GO


