/*
Missing Index Details from SQLQuery5.sql - RCASTILLO-PC\SODISARC.BIT_PROIMA (RCASTILLO-PC\RCASTILLO (63))
The Query Processor estimates that implementing the following index could improve the query cost by 62.1717%.
*/


USE [BIT_PROIMA]
GO
CREATE NONCLUSTERED INDEX [REM_TRF]
ON [dbo].[TRANSFERENCIA_INVENTA3E4T] ([FECHA_TRANSFERENCIA_RECIB],[CANTIDAD_RECIBIDA])
INCLUDE ([NUMERO_DE_TRANSFERENCIA],[CODIGO_DE_ARTICULO],[NUMERO_DE_LINEA],[CODIGO_DE_EMPAQUE],[CODIGO_UNIDAD_DE_MEDIDA],[BODEGA_ORIGEN_CODIGO_DE_B],[BODEGA_DESTINO_CODIGO_DE],[CODIGO_LOTE_SERIE],[LOTE],[FECHA_TRANSFERENCIA_ENTRE],[CANTIDAD_A_TRANSFERIR],[VALOR_TOTAL_TRANSFERIDO],[VALOR_TOTAL_RECIBIDO],[CODIGO_DE_PROYECTO])
GO

