/*Eliminar las llaves primarias*/
DECLARE  @constraintname SYSNAME, @objectid VARCHAR(100),
           @sqlcmd         VARCHAR(1024)
DECLARE CONSTRAINTSCURSOR CURSOR  FOR
SELECT CONSTRAINT_NAME, TABLE_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE OBJECTPROPERTY(OBJECT_ID(constraint_name), 'IsPrimaryKey') = 1
AND table_name = 'TRN_CONVERSION_DETALLE'
GROUP BY CONSTRAINT_NAME, TABLE_NAME
OPEN CONSTRAINTSCURSOR
FETCH NEXT FROM CONSTRAINTSCURSOR
INTO @constraintname, @objectid
WHILE (@@FETCH_STATUS = 0)
BEGIN
    SELECT @sqlcmd = 'ALTER TABLE ' + @objectid + ' DROP CONSTRAINT ' + @constraintname
    EXEC( @sqlcmd)
    FETCH NEXT FROM CONSTRAINTSCURSOR
    INTO @constraintname, @objectid
END
CLOSE CONSTRAINTSCURSOR
DEALLOCATE CONSTRAINTSCURSOR

/*Actualizar el Valor a Blanco*/
UPDATE    TRN_CONVERSION_DETALLE
SET              CODIGO_BIC = ''
WHERE     (CODIGO_BIC IS NULL)

/*Actualizar el campo a Not null*/
ALTER TABLE TRN_CONVERSION_DETALLE ALTER COLUMN CODIGO_BIC INTEGER NOT NULL

/*Poner las Nuevas Llaves*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.TRN_CONVERSION_DETALLE ADD CONSTRAINT
	PK_TRN_CONVERSION_DETALLE PRIMARY KEY CLUSTERED 
	(
	DEFINICION_DEL_PROCESO,
	CORRELATIVO_ICP,
	CORRELATIVO,
	CODIGO_DE_AGENCIA,
	CODIGO_BIC
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.TRN_CONVERSION_DETALLE SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

