
/****** Object:  Table [dbo].[TRN_CONVERSION_DETALLE]    Script Date: 05/03/2016 09:45:33 a.m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TRN_CONVERSION_DETALLE](
	[DEFINICION_DEL_PROCESO] [char](6) NOT NULL,
	[CORRELATIVO_ICP] [int] NOT NULL,
	[CORRELATIVO] [int] NOT NULL,
	[CODIGO_DE_AGENCIA] [int] NOT NULL,
	[ANO_DE_INVENTARIO] [int] NULL,
	[CODIGO_DE_ARTICULO] [char](15) NULL,
	[CODIGO_DE_EMPAQUE] [char](6) NULL,
	[CODIGO_UNIDAD_DE_MEDIDA] [char](6) NULL,
	[UNIDAD_MEDIDA_BASE] [char](6) NULL,
	[CODIGO_DE_BODEGA] [char](2) NULL,
	[CODIGO_LOTE_SERIE] [char](25) NULL,
	[LOTE] [int] NULL,
	[VALOR_DEBITO_MONEDA_ORIGE] [money] NULL,
	[VALOR_DEBITO_MONEDA_FINAN] [money] NULL,
	[VALOR_DEBITO_MONEDA_REEXP] [money] NULL,
	[UNIDADES_DEBITO_INV] [money] NULL,
	[CANTIDAD_ENTREGADA] [money] NULL,
	[CODIGO_BIC] [char](8) NULL,
 CONSTRAINT [PK__TRN_CONV__9F64E35224FE1D0A] PRIMARY KEY CLUSTERED 
(
	[DEFINICION_DEL_PROCESO] ASC,
	[CORRELATIVO_ICP] ASC,
	[CORRELATIVO] ASC,
	[CODIGO_DE_AGENCIA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


