BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.PUESTO_PHYSICAL_TABLE ADD
	CODIGO_CENTRO_DE_COSTO char(6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	AGRUPACION_CENTRO_DE_COSTO char(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CODIGO_TIPO_DE_GASTO char(6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CODIGO_DE_AGENCIA int NULL
GO
ALTER TABLE dbo.PUESTO_PHYSICAL_TABLE SET (LOCK_ESCALATION = TABLE)
GO
COMMIT