/****** Object:  Table [dbo].[PUESTO_HABILIDADES_REQUET]    Script Date: 06/07/2016 11:52:45 a.m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PUESTO_HABILIDADES_REQUET](
	[CODIGO_DE_PUESTO] [char](6) NOT NULL,
	[CODIGO_DE_HABILIDAD] [char](6) NOT NULL,
	[HORA_ADICION] [datetime] NULL,
	[FECHA_ADICION] [datetime] NULL,
	[USUARIO_ADICION] [varchar](128) NULL,
	[HORA_ULTIMO_CAMBIO] [datetime] NULL,
	[FECHA_ULTIMO_CAMBIO] [datetime] NULL,
	[USUARIO_ULTIMO_CAMBIO] [varchar](128) NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO_DE_PUESTO] ASC,
	[CODIGO_DE_HABILIDAD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[PUESTO_HABILIDADES_REQUET]  WITH CHECK ADD FOREIGN KEY([CODIGO_DE_HABILIDAD])
REFERENCES [dbo].[HABILIDADES_PHYSICAL_TABT] ([CODIGO_DE_HABILIDAD])
GO

ALTER TABLE [dbo].[PUESTO_HABILIDADES_REQUET]  WITH CHECK ADD FOREIGN KEY([CODIGO_DE_PUESTO])
REFERENCES [dbo].[PUESTO_PHYSICAL_TABLE] ([CODIGO_DE_PUESTO])
GO


