BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE HABILIDADES_PHYSICAL_TABT

ALTER COLUMN DESCRIPCION_DE_HABILIDAD char(250)
GO
ALTER TABLE dbo.HABILIDADES_PHYSICAL_TABT SET (LOCK_ESCALATION = TABLE)
GO
COMMIT