

/****** Object:  Table [dbo].[PUESTO_EDUCACION_REQUERIT]    Script Date: 06/07/2016 11:51:38 a.m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PUESTO_EDUCACION_REQUERIT](
	[CODIGO_DE_PUESTO] [char](6) NOT NULL,
	[NIVEL_DE_EDUCACION] [char](2) NOT NULL,
	[HORA_ADICION] [datetime] NULL,
	[FECHA_ADICION] [datetime] NULL,
	[USUARIO_ADICION] [varchar](128) NULL,
	[HORA_ULTIMO_CAMBIO] [datetime] NULL,
	[FECHA_ULTIMO_CAMBIO] [datetime] NULL,
	[USUARIO_ULTIMO_CAMBIO] [varchar](128) NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO_DE_PUESTO] ASC,
	[NIVEL_DE_EDUCACION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[PUESTO_EDUCACION_REQUERIT]  WITH CHECK ADD FOREIGN KEY([CODIGO_DE_PUESTO])
REFERENCES [dbo].[PUESTO_PHYSICAL_TABLE] ([CODIGO_DE_PUESTO])
GO

ALTER TABLE [dbo].[PUESTO_EDUCACION_REQUERIT]  WITH CHECK ADD FOREIGN KEY([NIVEL_DE_EDUCACION])
REFERENCES [dbo].[NIVEL_DE_EDUCACION_TABLA] ([NIVEL_DE_EDUCACION])
GO


