BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE NIVEL_DE_EDUCACION_TABLA

ALTER COLUMN NOMBRE_NIVEL_EDUCATIVO char(250)
GO
ALTER TABLE dbo.NIVEL_DE_EDUCACION_TABLA SET (LOCK_ESCALATION = TABLE)
GO
COMMIT