/****** Object:  Table [dbo].[ENCARGADO_DE_COMPRA_NIVELES_AUT]    Script Date: 7/15/2015 7:29:08 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ENCARGADO_DE_COMPRA_NIVELES_AUT](
	[OS4sA] [char](32) NOT NULL,
	[DESDE_VALOR_TOTAL] [money] NULL,
	[HASTA_VALOR_TOTAL] [money] NULL,
	[HORA_ADICION] [datetime] NULL,
	[FECHA_ADICION] [datetime] NULL,
	[USUARIO_ADICION] [varchar](128) NULL,
	[HORA_ULTIMO_CAMBIO] [datetime] NULL,
	[FECHA_ULTIMO_CAMBIO] [datetime] NULL,
	[USUARIO_ULTIMO_CAMBIO] [varchar](128) NULL,
PRIMARY KEY CLUSTERED 
(
	[OS4sA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[ENCARGADO_DE_COMPRA_NIVELES_AUT]  WITH CHECK ADD FOREIGN KEY([OS4sA])
REFERENCES [dbo].[OS12T] ([OS4sA])
GO