CREATE TABLE [dbo].[ORDEN_COMPRA_CTRL_N](
	[CODIGO_DE_AGENCIA] [int] NOT NULL,
	[NUMERO_ORDEN_DE_COMPRA] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO_DE_AGENCIA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[ORDEN_COMPRA_CTRL_N]  WITH CHECK ADD FOREIGN KEY([CODIGO_DE_AGENCIA])
REFERENCES [dbo].[AGENCIA] ([CODIGO_DE_AGENCIA])
GO


