SELECT    *-- COUNT(*) AS FECHAS_TRASLAPADAS
FROM         CICLO_DE_FINCA_LAGUNA_PHT
WHERE     
--(CODIGO_BIC = '&(1:)') AND (LAGUNA = '&(2:)') 
--AND 
(CONVERT(DATETIME, '2016-07-31 00:00:00', 102) BETWEEN FECHA_DE_INICIO AND FECHA_DE_CIERRE)