BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.EMPLEADO_TIEMPOS_RELOJ_OTROS ADD
	CODIGO_CENTRO_DE_COSTO char(6) NULL,
	AGRUPACION_CENTRO_DE_COSTO char(10) NULL,
	HORA_ADICION datetime NULL,
	FECHA_ADICION datetime NULL,
	USUARIO_ADICION varchar(128) NULL,
	HORA_ULTIMO_CAMBIO datetime NULL,
	FECHA_ULTIMO_CAMBIO datetime NULL,
	USUARIO_ULTIMO_CAMBIO varchar(128) NULL
GO
ALTER TABLE dbo.EMPLEADO_TIEMPOS_RELOJ_OTROS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
