
/****** Object:  Table [dbo].[TRANSACCIONES_PLA_TEMP_PDA_TG]    Script Date: 12/3/2015 12:47:16 AM ******/
DROP TABLE [dbo].[TRANSACCIONES_PLA_TEMP_PDA_TG]
GO

/****** Object:  Table [dbo].[TRANSACCIONES_PLA_TEMP_PDA_TG]    Script Date: 12/3/2015 12:47:16 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TRANSACCIONES_PLA_TEMP_PDA_TG](
	[CODIGO_CLASE_DE_PLANILLA] [char](2) NOT NULL,
	[CODIGO_TIPO_DE_PLANILLA] [char](2) NOT NULL,
	[ANO_PLANILLA] [int] NOT NULL,
	[PERIODO_PLANILLA] [int] NOT NULL,
	[TIPO_DEF_TRN_PLANILLA] [char](1) NOT NULL,
	[CODIGO_DE_CUENTA] [char](25) NOT NULL,
	[CODIGO_BIC] [char](8) NOT NULL,
	[CREDITO_RESERVA_CODIGO_DE_CUEN] [char](25) NOT NULL,
	[CODIGO_TIPO_DE_GASTO] [char](6) NOT NULL,
	[VALOR_CALCULO] [money] NULL,
	[CODIGO_DE_AGENCIA] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO_CLASE_DE_PLANILLA] ASC,
	[CODIGO_TIPO_DE_PLANILLA] ASC,
	[ANO_PLANILLA] ASC,
	[PERIODO_PLANILLA] ASC,
	[TIPO_DEF_TRN_PLANILLA] ASC,
	[CODIGO_DE_CUENTA] ASC,
	[CODIGO_BIC] ASC,
	[CREDITO_RESERVA_CODIGO_DE_CUEN] ASC,
	[CODIGO_TIPO_DE_GASTO] ASC,
	[CODIGO_DE_AGENCIA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


