CREATE VIEW [dbo].[ORDEN_COMPRA_U_PRECIO]
AS
SELECT  A.NUMERO_ORDEN_DE_COMPRA, A.CODIGO_DE_AGENCIA, A.NUMERO_DE_LINEA, A.CODIGO_DE_ARTICULO, A.DESCRIPCION_DEL_ARTICULO, A.CODIGO_DE_EMPAQUE, 
A.CODIGO_UNIDAD_DE_MEDIDA, A.CANTIDAD_A_COMPRAR, A.VALOR_TOTAL, A.IMPUESTO_INCLUIDO, A.COMENTARIOS, A.EXENTA, A.TIPO_DE_ARTICULO_A_COMPRA, 
A.NUMERO_DE_COTIZACION, A.CODIGO_BIC, A.NUMERO_DE_RESOLUCION_DEI, A.LINEA, A.DESCUENTO, A.PORCENTAJE_DE_DESCUENTO, A.VALOR_DEL_IMPUESTO, 
A.CODIGO_DE_PROYECTO, A.COMPRADO_TOTALMENTE_SINO,
ISNULL((SELECT TOP 1 (ORDEN_COMPRA_DET.VALOR_TOTAL+ORDEN_COMPRA_DET.VALOR_DEL_IMPUESTO - ORDEN_COMPRA_DET.DESCUENTO)/ORDEN_COMPRA_DET.CANTIDAD_A_COMPRAR
FROM ORDEN_COMPRA_DET INNER JOIN
ORDEN_COMPRA_CTRL ON ORDEN_COMPRA_DET.NUMERO_ORDEN_DE_COMPRA = ORDEN_COMPRA_CTRL.NUMERO_ORDEN_DE_COMPRA AND 
ORDEN_COMPRA_DET.CODIGO_DE_AGENCIA = ORDEN_COMPRA_CTRL.CODIGO_DE_AGENCIA
WHERE (ORDEN_COMPRA_DET.CODIGO_DE_AGENCIA = A.CODIGO_DE_AGENCIA) AND (ORDEN_COMPRA_DET.CODIGO_DE_ARTICULO = A.CODIGO_DE_ARTICULO) AND (ORDEN_COMPRA_DET.CODIGO_DE_EMPAQUE = A.CODIGO_DE_EMPAQUE) AND 
(ORDEN_COMPRA_DET.CODIGO_UNIDAD_DE_MEDIDA = A.CODIGO_UNIDAD_DE_MEDIDA) AND (ORDEN_COMPRA_CTRL.FECHA_DE_ORDEN <= B.FECHA_DE_ORDEN) AND (ORDEN_COMPRA_CTRL.NUMERO_ORDEN_DE_COMPRA <> A.NUMERO_ORDEN_DE_COMPRA)
ORDER BY ORDEN_COMPRA_CTRL.FECHA_DE_ORDEN DESC, ORDEN_COMPRA_CTRL.NUMERO_ORDEN_DE_COMPRA DESC),0) AS ULTIMO_PRECIO
FROM ORDEN_COMPRA_DET AS A INNER JOIN ORDEN_COMPRA_CTRL AS B ON A.NUMERO_ORDEN_DE_COMPRA = B.NUMERO_ORDEN_DE_COMPRA
AND A.CODIGO_DE_AGENCIA = B.CODIGO_DE_AGENCIA
WHERE (A.TIPO_DE_ARTICULO_A_COMPRA = 1)