/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.REQUISICION_DE_INVENTARIO_DT_GRD ADD
	CANTIDAD_ENTREGADA_11_CAN money NULL,
	CANTIDAD_ENTREGADA_12_CAN money NULL,
	CANTIDAD_ENTREGADA_13_CAN money NULL,
	CANTIDAD_ENTREGADA_14_CAN money NULL,
	CANTIDAD_ENTREGADA_15_CAN money NULL,
	CANTIDAD_ENTREGADA_16_CAN money NULL,
	CANTIDAD_ENTREGADA_17_CAN money NULL,
	CANTIDAD_ENTREGADA_18_CAN money NULL,
	CANTIDAD_ENTREGADA_19_CAN money NULL,
	CANTIDAD_ENTREGADA_20_CAN money NULL
GO
ALTER TABLE dbo.REQUISICION_DE_INVENTARIO_DT_GRD SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
